<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="21" passed="9" failed="12" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-05-03T17:41:27 ART" name="Suite" finished-at="2023-05-03T17:41:46 ART" duration-ms="19068">
    <groups>
    </groups>
    <test started-at="2023-05-03T17:41:27 ART" name="Test" finished-at="2023-05-03T17:41:46 ART" duration-ms="19068">
      <class name="github.SauceDemo.Login_Chrome">
        <test-method is-config="true" signature="driver_Setup()[pri:0, instance:github.SauceDemo.Login_Chrome@7139992f]" started-at="2023-05-03T17:41:20 ART" name="driver_Setup" description="driver setup" finished-at="2023-05-03T17:41:22 ART" duration-ms="1794" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- driver_Setup -->
        <test-method is-config="true" signature="browser_Setup()[pri:0, instance:github.SauceDemo.Login_Chrome@7139992f]" started-at="2023-05-03T17:41:27 ART" name="browser_Setup" description="browser setup" finished-at="2023-05-03T17:41:28 ART" duration-ms="408" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browser_Setup -->
        <test-method signature="login_Firefox_Credentials_Lockout()[pri:0, instance:github.SauceDemo.Login_Chrome@7139992f]" started-at="2023-05-03T17:41:38 ART" name="login_Firefox_Credentials_Lockout" description="Login with lockout user" finished-at="2023-05-03T17:41:39 ART" duration-ms="366" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[did not expect [https://www.saucedemo.com/] but found [https://www.saucedemo.com/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: did not expect [https://www.saucedemo.com/] but found [https://www.saucedemo.com/]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failEquals(Assert.java:1581)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:156)
at org.testng.Assert.assertNotEquals(Assert.java:2197)
at org.testng.Assert.assertNotEquals(Assert.java:2219)
at github.SauceDemo.Login_Chrome.login_Firefox_Credentials_Lockout(Login_Chrome.java:104)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_Firefox_Credentials_Lockout -->
        <test-method is-config="true" signature="cleanBrowser()[pri:0, instance:github.SauceDemo.Login_Chrome@7139992f]" started-at="2023-05-03T17:41:39 ART" name="cleanBrowser" finished-at="2023-05-03T17:41:39 ART" duration-ms="54" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanBrowser -->
        <test-method signature="login_Firefox_Credentials_None()[pri:0, instance:github.SauceDemo.Login_Chrome@7139992f]" started-at="2023-05-03T17:41:39 ART" name="login_Firefox_Credentials_None" description="Login without credentials" finished-at="2023-05-03T17:41:39 ART" duration-ms="199" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[did not expect [https://www.saucedemo.com/] but found [https://www.saucedemo.com/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: did not expect [https://www.saucedemo.com/] but found [https://www.saucedemo.com/]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failEquals(Assert.java:1581)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:156)
at org.testng.Assert.assertNotEquals(Assert.java:2197)
at org.testng.Assert.assertNotEquals(Assert.java:2219)
at github.SauceDemo.Login_Chrome.login_Firefox_Credentials_None(Login_Chrome.java:180)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_Firefox_Credentials_None -->
        <test-method is-config="true" signature="cleanBrowser()[pri:0, instance:github.SauceDemo.Login_Chrome@7139992f]" started-at="2023-05-03T17:41:39 ART" name="cleanBrowser" finished-at="2023-05-03T17:41:39 ART" duration-ms="23" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanBrowser -->
        <test-method signature="login_Firefox_Credentials_Ok()[pri:0, instance:github.SauceDemo.Login_Chrome@7139992f]" started-at="2023-05-03T17:41:39 ART" name="login_Firefox_Credentials_Ok" description="Login with correct credentials" finished-at="2023-05-03T17:41:40 ART" duration-ms="622" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_Firefox_Credentials_Ok -->
        <test-method is-config="true" signature="cleanBrowser()[pri:0, instance:github.SauceDemo.Login_Chrome@7139992f]" started-at="2023-05-03T17:41:40 ART" name="cleanBrowser" finished-at="2023-05-03T17:41:40 ART" duration-ms="31" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanBrowser -->
        <test-method signature="login_Firefox_Credentials_Password_Wrong()[pri:0, instance:github.SauceDemo.Login_Chrome@7139992f]" started-at="2023-05-03T17:41:40 ART" name="login_Firefox_Credentials_Password_Wrong" description="Login with wrong credentials: Password" finished-at="2023-05-03T17:41:40 ART" duration-ms="282" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[did not expect [https://www.saucedemo.com/] but found [https://www.saucedemo.com/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: did not expect [https://www.saucedemo.com/] but found [https://www.saucedemo.com/]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failEquals(Assert.java:1581)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:156)
at org.testng.Assert.assertNotEquals(Assert.java:2197)
at org.testng.Assert.assertNotEquals(Assert.java:2219)
at github.SauceDemo.Login_Chrome.login_Firefox_Credentials_Password_Wrong(Login_Chrome.java:164)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_Firefox_Credentials_Password_Wrong -->
        <test-method is-config="true" signature="cleanBrowser()[pri:0, instance:github.SauceDemo.Login_Chrome@7139992f]" started-at="2023-05-03T17:41:40 ART" name="cleanBrowser" finished-at="2023-05-03T17:41:40 ART" duration-ms="42" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanBrowser -->
        <test-method signature="login_Firefox_Credentials_Username_Wrong()[pri:0, instance:github.SauceDemo.Login_Chrome@7139992f]" started-at="2023-05-03T17:41:40 ART" name="login_Firefox_Credentials_Username_Wrong" description="Login with wrong credentials: Username" finished-at="2023-05-03T17:41:40 ART" duration-ms="347" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[did not expect [https://www.saucedemo.com/] but found [https://www.saucedemo.com/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: did not expect [https://www.saucedemo.com/] but found [https://www.saucedemo.com/]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failEquals(Assert.java:1581)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:156)
at org.testng.Assert.assertNotEquals(Assert.java:2197)
at org.testng.Assert.assertNotEquals(Assert.java:2219)
at github.SauceDemo.Login_Chrome.login_Firefox_Credentials_Username_Wrong(Login_Chrome.java:125)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_Firefox_Credentials_Username_Wrong -->
        <test-method is-config="true" signature="cleanBrowser()[pri:0, instance:github.SauceDemo.Login_Chrome@7139992f]" started-at="2023-05-03T17:41:40 ART" name="cleanBrowser" finished-at="2023-05-03T17:41:40 ART" duration-ms="37" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanBrowser -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:github.SauceDemo.Login_Chrome@7139992f]" started-at="2023-05-03T17:41:45 ART" name="closeBrowser" description="Close browser" finished-at="2023-05-03T17:41:45 ART" duration-ms="189" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="showConsoleMessage()[pri:0, instance:github.SauceDemo.Login_Chrome@7139992f]" started-at="2023-05-03T17:41:46 ART" name="showConsoleMessage" description="Show message in console" finished-at="2023-05-03T17:41:46 ART" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- showConsoleMessage -->
      </class> <!-- github.SauceDemo.Login_Chrome -->
      <class name="github.SauceDemo.Login_Edge">
        <test-method is-config="true" signature="driver_Setup()[pri:0, instance:github.SauceDemo.Login_Edge@69504ae9]" started-at="2023-05-03T17:41:22 ART" name="driver_Setup" description="driver setup" finished-at="2023-05-03T17:41:23 ART" duration-ms="798" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- driver_Setup -->
        <test-method is-config="true" signature="browser_Setup()[pri:0, instance:github.SauceDemo.Login_Edge@69504ae9]" started-at="2023-05-03T17:41:28 ART" name="browser_Setup" description="browser setup" finished-at="2023-05-03T17:41:28 ART" duration-ms="484" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browser_Setup -->
        <test-method signature="login_Firefox_Credentials_Lockout()[pri:0, instance:github.SauceDemo.Login_Edge@69504ae9]" started-at="2023-05-03T17:41:40 ART" name="login_Firefox_Credentials_Lockout" description="Login with lockout user" finished-at="2023-05-03T17:41:41 ART" duration-ms="379" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[did not expect [https://www.saucedemo.com/] but found [https://www.saucedemo.com/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: did not expect [https://www.saucedemo.com/] but found [https://www.saucedemo.com/]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failEquals(Assert.java:1581)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:156)
at org.testng.Assert.assertNotEquals(Assert.java:2197)
at org.testng.Assert.assertNotEquals(Assert.java:2219)
at github.SauceDemo.Login_Edge.login_Firefox_Credentials_Lockout(Login_Edge.java:104)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_Firefox_Credentials_Lockout -->
        <test-method is-config="true" signature="cleanBrowser()[pri:0, instance:github.SauceDemo.Login_Edge@69504ae9]" started-at="2023-05-03T17:41:41 ART" name="cleanBrowser" finished-at="2023-05-03T17:41:41 ART" duration-ms="50" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanBrowser -->
        <test-method signature="login_Firefox_Credentials_None()[pri:0, instance:github.SauceDemo.Login_Edge@69504ae9]" started-at="2023-05-03T17:41:41 ART" name="login_Firefox_Credentials_None" description="Login without credentials" finished-at="2023-05-03T17:41:41 ART" duration-ms="189" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[did not expect [https://www.saucedemo.com/] but found [https://www.saucedemo.com/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: did not expect [https://www.saucedemo.com/] but found [https://www.saucedemo.com/]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failEquals(Assert.java:1581)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:156)
at org.testng.Assert.assertNotEquals(Assert.java:2197)
at org.testng.Assert.assertNotEquals(Assert.java:2219)
at github.SauceDemo.Login_Edge.login_Firefox_Credentials_None(Login_Edge.java:180)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_Firefox_Credentials_None -->
        <test-method is-config="true" signature="cleanBrowser()[pri:0, instance:github.SauceDemo.Login_Edge@69504ae9]" started-at="2023-05-03T17:41:41 ART" name="cleanBrowser" finished-at="2023-05-03T17:41:41 ART" duration-ms="33" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanBrowser -->
        <test-method signature="login_Firefox_Credentials_Ok()[pri:0, instance:github.SauceDemo.Login_Edge@69504ae9]" started-at="2023-05-03T17:41:41 ART" name="login_Firefox_Credentials_Ok" description="Login with correct credentials" finished-at="2023-05-03T17:41:42 ART" duration-ms="658" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_Firefox_Credentials_Ok -->
        <test-method is-config="true" signature="cleanBrowser()[pri:0, instance:github.SauceDemo.Login_Edge@69504ae9]" started-at="2023-05-03T17:41:42 ART" name="cleanBrowser" finished-at="2023-05-03T17:41:42 ART" duration-ms="44" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanBrowser -->
        <test-method signature="login_Firefox_Credentials_Password_Wrong()[pri:0, instance:github.SauceDemo.Login_Edge@69504ae9]" started-at="2023-05-03T17:41:42 ART" name="login_Firefox_Credentials_Password_Wrong" description="Login with wrong credentials: Password" finished-at="2023-05-03T17:41:42 ART" duration-ms="302" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[did not expect [https://www.saucedemo.com/] but found [https://www.saucedemo.com/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: did not expect [https://www.saucedemo.com/] but found [https://www.saucedemo.com/]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failEquals(Assert.java:1581)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:156)
at org.testng.Assert.assertNotEquals(Assert.java:2197)
at org.testng.Assert.assertNotEquals(Assert.java:2219)
at github.SauceDemo.Login_Edge.login_Firefox_Credentials_Password_Wrong(Login_Edge.java:164)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_Firefox_Credentials_Password_Wrong -->
        <test-method is-config="true" signature="cleanBrowser()[pri:0, instance:github.SauceDemo.Login_Edge@69504ae9]" started-at="2023-05-03T17:41:42 ART" name="cleanBrowser" finished-at="2023-05-03T17:41:42 ART" duration-ms="37" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanBrowser -->
        <test-method signature="login_Firefox_Credentials_Username_Wrong()[pri:0, instance:github.SauceDemo.Login_Edge@69504ae9]" started-at="2023-05-03T17:41:42 ART" name="login_Firefox_Credentials_Username_Wrong" description="Login with wrong credentials: Username" finished-at="2023-05-03T17:41:42 ART" duration-ms="380" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[did not expect [https://www.saucedemo.com/] but found [https://www.saucedemo.com/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: did not expect [https://www.saucedemo.com/] but found [https://www.saucedemo.com/]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failEquals(Assert.java:1581)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:156)
at org.testng.Assert.assertNotEquals(Assert.java:2197)
at org.testng.Assert.assertNotEquals(Assert.java:2219)
at github.SauceDemo.Login_Edge.login_Firefox_Credentials_Username_Wrong(Login_Edge.java:125)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_Firefox_Credentials_Username_Wrong -->
        <test-method is-config="true" signature="cleanBrowser()[pri:0, instance:github.SauceDemo.Login_Edge@69504ae9]" started-at="2023-05-03T17:41:42 ART" name="cleanBrowser" finished-at="2023-05-03T17:41:42 ART" duration-ms="34" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanBrowser -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:github.SauceDemo.Login_Edge@69504ae9]" started-at="2023-05-03T17:41:45 ART" name="closeBrowser" description="Close browser" finished-at="2023-05-03T17:41:45 ART" duration-ms="225" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="showConsoleMessage()[pri:0, instance:github.SauceDemo.Login_Edge@69504ae9]" started-at="2023-05-03T17:41:46 ART" name="showConsoleMessage" description="Show message in console" finished-at="2023-05-03T17:41:46 ART" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- showConsoleMessage -->
      </class> <!-- github.SauceDemo.Login_Edge -->
      <class name="github.SauceDemo.MakeSimpleOrder">
        <test-method is-config="true" signature="setUp()[pri:0, instance:github.SauceDemo.MakeSimpleOrder@63376bed]" started-at="2023-05-03T17:41:26 ART" name="setUp" description="driver setup" finished-at="2023-05-03T17:41:27 ART" duration-ms="829" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="logIn()[pri:0, instance:github.SauceDemo.MakeSimpleOrder@63376bed]" started-at="2023-05-03T17:41:30 ART" name="logIn" description="browser setup and login" finished-at="2023-05-03T17:41:31 ART" duration-ms="790" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logIn -->
        <test-method signature="productSortHiLo()[pri:0, instance:github.SauceDemo.MakeSimpleOrder@63376bed]" started-at="2023-05-03T17:41:31 ART" name="productSortHiLo" description="Sort products from higher to lower price" finished-at="2023-05-03T17:41:33 ART" duration-ms="1990" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- productSortHiLo -->
        <test-method signature="addToCartAndGoToCheckout()[pri:1, instance:github.SauceDemo.MakeSimpleOrder@63376bed]" started-at="2023-05-03T17:41:33 ART" name="addToCartAndGoToCheckout" description="Add two items to cart" finished-at="2023-05-03T17:41:33 ART" duration-ms="423" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addToCartAndGoToCheckout -->
        <test-method signature="checkoutFinish()[pri:2, instance:github.SauceDemo.MakeSimpleOrder@63376bed]" started-at="2023-05-03T17:41:33 ART" name="checkoutFinish" description="Complete checkout info and buy items" finished-at="2023-05-03T17:41:35 ART" duration-ms="2194" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkoutFinish -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:github.SauceDemo.MakeSimpleOrder@63376bed]" started-at="2023-05-03T17:41:46 ART" name="closeBrowser" description="Close browser" finished-at="2023-05-03T17:41:46 ART" duration-ms="181" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="showConsoleMessage()[pri:0, instance:github.SauceDemo.MakeSimpleOrder@63376bed]" started-at="2023-05-03T17:41:46 ART" name="showConsoleMessage" description="Show message in console" finished-at="2023-05-03T17:41:46 ART" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- showConsoleMessage -->
      </class> <!-- github.SauceDemo.MakeSimpleOrder -->
      <class name="github.SauceDemo.Login_Firefox">
        <test-method is-config="true" signature="driver_Setup()[pri:0, instance:github.SauceDemo.Login_Firefox@387a8303]" started-at="2023-05-03T17:41:23 ART" name="driver_Setup" description="driver setup" finished-at="2023-05-03T17:41:26 ART" duration-ms="2925" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- driver_Setup -->
        <test-method is-config="true" signature="browser_Setup()[pri:0, instance:github.SauceDemo.Login_Firefox@387a8303]" started-at="2023-05-03T17:41:28 ART" name="browser_Setup" description="browser setup" finished-at="2023-05-03T17:41:29 ART" duration-ms="1164" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browser_Setup -->
        <test-method signature="login_Firefox_Credentials_Lockout()[pri:0, instance:github.SauceDemo.Login_Firefox@387a8303]" started-at="2023-05-03T17:41:42 ART" name="login_Firefox_Credentials_Lockout" description="Login with lockout user" finished-at="2023-05-03T17:41:43 ART" duration-ms="349" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[did not expect [https://www.saucedemo.com/] but found [https://www.saucedemo.com/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: did not expect [https://www.saucedemo.com/] but found [https://www.saucedemo.com/]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failEquals(Assert.java:1581)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:156)
at org.testng.Assert.assertNotEquals(Assert.java:2197)
at org.testng.Assert.assertNotEquals(Assert.java:2219)
at github.SauceDemo.Login_Firefox.login_Firefox_Credentials_Lockout(Login_Firefox.java:104)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_Firefox_Credentials_Lockout -->
        <test-method is-config="true" signature="cleanBrowser()[pri:0, instance:github.SauceDemo.Login_Firefox@387a8303]" started-at="2023-05-03T17:41:43 ART" name="cleanBrowser" finished-at="2023-05-03T17:41:43 ART" duration-ms="91" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanBrowser -->
        <test-method signature="login_Firefox_Credentials_None()[pri:0, instance:github.SauceDemo.Login_Firefox@387a8303]" started-at="2023-05-03T17:41:43 ART" name="login_Firefox_Credentials_None" description="Login without credentials" finished-at="2023-05-03T17:41:43 ART" duration-ms="286" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[did not expect [https://www.saucedemo.com/] but found [https://www.saucedemo.com/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: did not expect [https://www.saucedemo.com/] but found [https://www.saucedemo.com/]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failEquals(Assert.java:1581)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:156)
at org.testng.Assert.assertNotEquals(Assert.java:2197)
at org.testng.Assert.assertNotEquals(Assert.java:2219)
at github.SauceDemo.Login_Firefox.login_Firefox_Credentials_None(Login_Firefox.java:180)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_Firefox_Credentials_None -->
        <test-method is-config="true" signature="cleanBrowser()[pri:0, instance:github.SauceDemo.Login_Firefox@387a8303]" started-at="2023-05-03T17:41:43 ART" name="cleanBrowser" finished-at="2023-05-03T17:41:43 ART" duration-ms="98" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanBrowser -->
        <test-method signature="login_Firefox_Credentials_Ok()[pri:0, instance:github.SauceDemo.Login_Firefox@387a8303]" started-at="2023-05-03T17:41:43 ART" name="login_Firefox_Credentials_Ok" description="Login with correct credentials" finished-at="2023-05-03T17:41:44 ART" duration-ms="446" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_Firefox_Credentials_Ok -->
        <test-method is-config="true" signature="cleanBrowser()[pri:0, instance:github.SauceDemo.Login_Firefox@387a8303]" started-at="2023-05-03T17:41:44 ART" name="cleanBrowser" finished-at="2023-05-03T17:41:44 ART" duration-ms="102" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanBrowser -->
        <test-method signature="login_Firefox_Credentials_Password_Wrong()[pri:0, instance:github.SauceDemo.Login_Firefox@387a8303]" started-at="2023-05-03T17:41:44 ART" name="login_Firefox_Credentials_Password_Wrong" description="Login with wrong credentials: Password" finished-at="2023-05-03T17:41:44 ART" duration-ms="333" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[did not expect [https://www.saucedemo.com/] but found [https://www.saucedemo.com/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: did not expect [https://www.saucedemo.com/] but found [https://www.saucedemo.com/]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failEquals(Assert.java:1581)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:156)
at org.testng.Assert.assertNotEquals(Assert.java:2197)
at org.testng.Assert.assertNotEquals(Assert.java:2219)
at github.SauceDemo.Login_Firefox.login_Firefox_Credentials_Password_Wrong(Login_Firefox.java:164)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_Firefox_Credentials_Password_Wrong -->
        <test-method is-config="true" signature="cleanBrowser()[pri:0, instance:github.SauceDemo.Login_Firefox@387a8303]" started-at="2023-05-03T17:41:44 ART" name="cleanBrowser" finished-at="2023-05-03T17:41:44 ART" duration-ms="103" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanBrowser -->
        <test-method signature="login_Firefox_Credentials_Username_Wrong()[pri:0, instance:github.SauceDemo.Login_Firefox@387a8303]" started-at="2023-05-03T17:41:44 ART" name="login_Firefox_Credentials_Username_Wrong" description="Login with wrong credentials: Username" finished-at="2023-05-03T17:41:45 ART" duration-ms="318" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[did not expect [https://www.saucedemo.com/] but found [https://www.saucedemo.com/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: did not expect [https://www.saucedemo.com/] but found [https://www.saucedemo.com/]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failEquals(Assert.java:1581)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:156)
at org.testng.Assert.assertNotEquals(Assert.java:2197)
at org.testng.Assert.assertNotEquals(Assert.java:2219)
at github.SauceDemo.Login_Firefox.login_Firefox_Credentials_Username_Wrong(Login_Firefox.java:125)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_Firefox_Credentials_Username_Wrong -->
        <test-method is-config="true" signature="cleanBrowser()[pri:0, instance:github.SauceDemo.Login_Firefox@387a8303]" started-at="2023-05-03T17:41:45 ART" name="cleanBrowser" finished-at="2023-05-03T17:41:45 ART" duration-ms="95" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanBrowser -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:github.SauceDemo.Login_Firefox@387a8303]" started-at="2023-05-03T17:41:45 ART" name="closeBrowser" description="Close browser" finished-at="2023-05-03T17:41:46 ART" duration-ms="791" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="showConsoleMessage()[pri:0, instance:github.SauceDemo.Login_Firefox@387a8303]" started-at="2023-05-03T17:41:46 ART" name="showConsoleMessage" description="Show message in console" finished-at="2023-05-03T17:41:46 ART" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- showConsoleMessage -->
      </class> <!-- github.SauceDemo.Login_Firefox -->
      <class name="github.SauceDemo.MakeOrderAndDelete">
        <test-method is-config="true" signature="setUp()[pri:0, instance:github.SauceDemo.MakeOrderAndDelete@47caedad]" started-at="2023-05-03T17:41:26 ART" name="setUp" description="driver setup" finished-at="2023-05-03T17:41:26 ART" duration-ms="848" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="logIn()[pri:0, instance:github.SauceDemo.MakeOrderAndDelete@47caedad]" started-at="2023-05-03T17:41:29 ART" name="logIn" description="browser setup and login" finished-at="2023-05-03T17:41:30 ART" duration-ms="688" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logIn -->
        <test-method signature="productSortZA()[pri:0, instance:github.SauceDemo.MakeOrderAndDelete@47caedad]" started-at="2023-05-03T17:41:35 ART" name="productSortZA" description="Sort products from Z to A" finished-at="2023-05-03T17:41:37 ART" duration-ms="1719" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- productSortZA -->
        <test-method signature="addToCartAndGoToCheckout()[pri:1, instance:github.SauceDemo.MakeOrderAndDelete@47caedad]" started-at="2023-05-03T17:41:37 ART" name="addToCartAndGoToCheckout" description="Add random number of items to cart" finished-at="2023-05-03T17:41:38 ART" duration-ms="960" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addToCartAndGoToCheckout -->
        <test-method signature="checkoutFinish()[pri:2, instance:github.SauceDemo.MakeOrderAndDelete@47caedad]" started-at="2023-05-03T17:41:38 ART" name="checkoutFinish" description="Delete items from cart" finished-at="2023-05-03T17:41:38 ART" duration-ms="295" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkoutFinish -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:github.SauceDemo.MakeOrderAndDelete@47caedad]" started-at="2023-05-03T17:41:46 ART" name="closeBrowser" description="Close browser" finished-at="2023-05-03T17:41:46 ART" duration-ms="167" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="showConsoleMessage()[pri:0, instance:github.SauceDemo.MakeOrderAndDelete@47caedad]" started-at="2023-05-03T17:41:46 ART" name="showConsoleMessage" description="Show message in console" finished-at="2023-05-03T17:41:46 ART" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- showConsoleMessage -->
      </class> <!-- github.SauceDemo.MakeOrderAndDelete -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
